// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockCache
func (_mock *MockCache) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCache_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCache_Expecter) Close() *MockCache_Close_Call {
	return &MockCache_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCache_Close_Call) Run(run func()) *MockCache_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Close_Call) Return(err error) *MockCache_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Close_Call) RunAndReturn(run func() error) *MockCache_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetJSON provides a mock function for the type MockCache
func (_mock *MockCache) GetJSON(context1 context.Context, s string, v any) error {
	ret := _mock.Called(context1, s, v)

	if len(ret) == 0 {
		panic("no return value specified for GetJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(context1, s, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_GetJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJSON'
type MockCache_GetJSON_Call struct {
	*mock.Call
}

// GetJSON is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - v any
func (_e *MockCache_Expecter) GetJSON(context1 interface{}, s interface{}, v interface{}) *MockCache_GetJSON_Call {
	return &MockCache_GetJSON_Call{Call: _e.mock.On("GetJSON", context1, s, v)}
}

func (_c *MockCache_GetJSON_Call) Run(run func(context1 context.Context, s string, v any)) *MockCache_GetJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_GetJSON_Call) Return(err error) *MockCache_GetJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_GetJSON_Call) RunAndReturn(run func(context1 context.Context, s string, v any) error) *MockCache_GetJSON_Call {
	_c.Call.Return(run)
	return _c
}

// SetJSON provides a mock function for the type MockCache
func (_mock *MockCache) SetJSON(context1 context.Context, s string, v any, duration time.Duration) error {
	ret := _mock.Called(context1, s, v, duration)

	if len(ret) == 0 {
		panic("no return value specified for SetJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(context1, s, v, duration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_SetJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetJSON'
type MockCache_SetJSON_Call struct {
	*mock.Call
}

// SetJSON is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - v any
//   - duration time.Duration
func (_e *MockCache_Expecter) SetJSON(context1 interface{}, s interface{}, v interface{}, duration interface{}) *MockCache_SetJSON_Call {
	return &MockCache_SetJSON_Call{Call: _e.mock.On("SetJSON", context1, s, v, duration)}
}

func (_c *MockCache_SetJSON_Call) Run(run func(context1 context.Context, s string, v any, duration time.Duration)) *MockCache_SetJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCache_SetJSON_Call) Return(err error) *MockCache_SetJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_SetJSON_Call) RunAndReturn(run func(context1 context.Context, s string, v any, duration time.Duration) error) *MockCache_SetJSON_Call {
	_c.Call.Return(run)
	return _c
}

// SetNX provides a mock function for the type MockCache
func (_mock *MockCache) SetNX(context1 context.Context, s string, s1 string, duration time.Duration) (bool, error) {
	ret := _mock.Called(context1, s, s1, duration)

	if len(ret) == 0 {
		panic("no return value specified for SetNX")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (bool, error)); ok {
		return returnFunc(context1, s, s1, duration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) bool); ok {
		r0 = returnFunc(context1, s, s1, duration)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(context1, s, s1, duration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_SetNX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNX'
type MockCache_SetNX_Call struct {
	*mock.Call
}

// SetNX is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - duration time.Duration
func (_e *MockCache_Expecter) SetNX(context1 interface{}, s interface{}, s1 interface{}, duration interface{}) *MockCache_SetNX_Call {
	return &MockCache_SetNX_Call{Call: _e.mock.On("SetNX", context1, s, s1, duration)}
}

func (_c *MockCache_SetNX_Call) Run(run func(context1 context.Context, s string, s1 string, duration time.Duration)) *MockCache_SetNX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCache_SetNX_Call) Return(b bool, err error) *MockCache_SetNX_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCache_SetNX_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, duration time.Duration) (bool, error)) *MockCache_SetNX_Call {
	_c.Call.Return(run)
	return _c
}
