// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package aisignal

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChatClient creates a new instance of MockChatClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatClient {
	mock := &MockChatClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatClient is an autogenerated mock type for the ChatClient type
type MockChatClient struct {
	mock.Mock
}

type MockChatClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatClient) EXPECT() *MockChatClient_Expecter {
	return &MockChatClient_Expecter{mock: &_m.Mock}
}

// ChatJSON provides a mock function for the type MockChatClient
func (_mock *MockChatClient) ChatJSON(context1 context.Context, chatRequest ChatRequest) (string, error) {
	ret := _mock.Called(context1, chatRequest)

	if len(ret) == 0 {
		panic("no return value specified for ChatJSON")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatRequest) (string, error)); ok {
		return returnFunc(context1, chatRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatRequest) string); ok {
		r0 = returnFunc(context1, chatRequest)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ChatRequest) error); ok {
		r1 = returnFunc(context1, chatRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatClient_ChatJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatJSON'
type MockChatClient_ChatJSON_Call struct {
	*mock.Call
}

// ChatJSON is a helper method to define mock.On call
//   - context1 context.Context
//   - chatRequest ChatRequest
func (_e *MockChatClient_Expecter) ChatJSON(context1 interface{}, chatRequest interface{}) *MockChatClient_ChatJSON_Call {
	return &MockChatClient_ChatJSON_Call{Call: _e.mock.On("ChatJSON", context1, chatRequest)}
}

func (_c *MockChatClient_ChatJSON_Call) Run(run func(context1 context.Context, chatRequest ChatRequest)) *MockChatClient_ChatJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChatRequest
		if args[1] != nil {
			arg1 = args[1].(ChatRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatClient_ChatJSON_Call) Return(s string, err error) *MockChatClient_ChatJSON_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChatClient_ChatJSON_Call) RunAndReturn(run func(context1 context.Context, chatRequest ChatRequest) (string, error)) *MockChatClient_ChatJSON_Call {
	_c.Call.Return(run)
	return _c
}
