// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package executionengine

import (
	"context"

	model0 "github.com/local/polymarket-process-service/pkg/model/execution"
	"github.com/local/polymarket-process-service/pkg/model/position"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutionProvider creates a new instance of MockExecutionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutionProvider {
	mock := &MockExecutionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutionProvider is an autogenerated mock type for the ExecutionProvider type
type MockExecutionProvider struct {
	mock.Mock
}

type MockExecutionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutionProvider) EXPECT() *MockExecutionProvider_Expecter {
	return &MockExecutionProvider_Expecter{mock: &_m.Mock}
}

// ClosePosition provides a mock function for the type MockExecutionProvider
func (_mock *MockExecutionProvider) ClosePosition(context1 context.Context, position model.Position, s string) (model0.OrderResult, error) {
	ret := _mock.Called(context1, position, s)

	if len(ret) == 0 {
		panic("no return value specified for ClosePosition")
	}

	var r0 model0.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Position, string) (model0.OrderResult, error)); ok {
		return returnFunc(context1, position, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Position, string) model0.OrderResult); ok {
		r0 = returnFunc(context1, position, s)
	} else {
		r0 = ret.Get(0).(model0.OrderResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Position, string) error); ok {
		r1 = returnFunc(context1, position, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutionProvider_ClosePosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosePosition'
type MockExecutionProvider_ClosePosition_Call struct {
	*mock.Call
}

// ClosePosition is a helper method to define mock.On call
//   - context1 context.Context
//   - position model.Position
//   - s string
func (_e *MockExecutionProvider_Expecter) ClosePosition(context1 interface{}, position interface{}, s interface{}) *MockExecutionProvider_ClosePosition_Call {
	return &MockExecutionProvider_ClosePosition_Call{Call: _e.mock.On("ClosePosition", context1, position, s)}
}

func (_c *MockExecutionProvider_ClosePosition_Call) Run(run func(context1 context.Context, position model.Position, s string)) *MockExecutionProvider_ClosePosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Position
		if args[1] != nil {
			arg1 = args[1].(model.Position)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExecutionProvider_ClosePosition_Call) Return(orderResult model0.OrderResult, err error) *MockExecutionProvider_ClosePosition_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockExecutionProvider_ClosePosition_Call) RunAndReturn(run func(context1 context.Context, position model.Position, s string) (model0.OrderResult, error)) *MockExecutionProvider_ClosePosition_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceOrder provides a mock function for the type MockExecutionProvider
func (_mock *MockExecutionProvider) PlaceOrder(context1 context.Context, orderRequest model0.OrderRequest) (model0.OrderResult, error) {
	ret := _mock.Called(context1, orderRequest)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 model0.OrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model0.OrderRequest) (model0.OrderResult, error)); ok {
		return returnFunc(context1, orderRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model0.OrderRequest) model0.OrderResult); ok {
		r0 = returnFunc(context1, orderRequest)
	} else {
		r0 = ret.Get(0).(model0.OrderResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model0.OrderRequest) error); ok {
		r1 = returnFunc(context1, orderRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutionProvider_PlaceOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceOrder'
type MockExecutionProvider_PlaceOrder_Call struct {
	*mock.Call
}

// PlaceOrder is a helper method to define mock.On call
//   - context1 context.Context
//   - orderRequest model0.OrderRequest
func (_e *MockExecutionProvider_Expecter) PlaceOrder(context1 interface{}, orderRequest interface{}) *MockExecutionProvider_PlaceOrder_Call {
	return &MockExecutionProvider_PlaceOrder_Call{Call: _e.mock.On("PlaceOrder", context1, orderRequest)}
}

func (_c *MockExecutionProvider_PlaceOrder_Call) Run(run func(context1 context.Context, orderRequest model0.OrderRequest)) *MockExecutionProvider_PlaceOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model0.OrderRequest
		if args[1] != nil {
			arg1 = args[1].(model0.OrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExecutionProvider_PlaceOrder_Call) Return(orderResult model0.OrderResult, err error) *MockExecutionProvider_PlaceOrder_Call {
	_c.Call.Return(orderResult, err)
	return _c
}

func (_c *MockExecutionProvider_PlaceOrder_Call) RunAndReturn(run func(context1 context.Context, orderRequest model0.OrderRequest) (model0.OrderResult, error)) *MockExecutionProvider_PlaceOrder_Call {
	_c.Call.Return(run)
	return _c
}
