// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	model5 "github.com/local/polymarket-fetch-data-service/pkg/model/ai"
	model4 "github.com/local/polymarket-fetch-data-service/pkg/model/execution"
	"github.com/local/polymarket-fetch-data-service/pkg/model/market"
	model6 "github.com/local/polymarket-fetch-data-service/pkg/model/match"
	model0 "github.com/local/polymarket-fetch-data-service/pkg/model/news"
	model1 "github.com/local/polymarket-fetch-data-service/pkg/model/position"
	model2 "github.com/local/polymarket-fetch-data-service/pkg/model/probability"
	model3 "github.com/local/polymarket-fetch-data-service/pkg/model/risk"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStore
func (_mock *MockStore) Close() {
	_mock.Called()
	return
}

// MockStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStore_Expecter) Close() *MockStore_Close_Call {
	return &MockStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStore_Close_Call) Run(run func()) *MockStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Close_Call) Return() *MockStore_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStore_Close_Call) RunAndReturn(run func()) *MockStore_Close_Call {
	_c.Run(run)
	return _c
}

// GetLiveMarketState provides a mock function for the type MockStore
func (_mock *MockStore) GetLiveMarketState(context1 context.Context, s string) (model.LiveMarketState, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetLiveMarketState")
	}

	var r0 model.LiveMarketState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.LiveMarketState, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.LiveMarketState); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.LiveMarketState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetLiveMarketState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLiveMarketState'
type MockStore_GetLiveMarketState_Call struct {
	*mock.Call
}

// GetLiveMarketState is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) GetLiveMarketState(context1 interface{}, s interface{}) *MockStore_GetLiveMarketState_Call {
	return &MockStore_GetLiveMarketState_Call{Call: _e.mock.On("GetLiveMarketState", context1, s)}
}

func (_c *MockStore_GetLiveMarketState_Call) Run(run func(context1 context.Context, s string)) *MockStore_GetLiveMarketState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetLiveMarketState_Call) Return(liveMarketState model.LiveMarketState, err error) *MockStore_GetLiveMarketState_Call {
	_c.Call.Return(liveMarketState, err)
	return _c
}

func (_c *MockStore_GetLiveMarketState_Call) RunAndReturn(run func(context1 context.Context, s string) (model.LiveMarketState, error)) *MockStore_GetLiveMarketState_Call {
	_c.Call.Return(run)
	return _c
}

// GetMarket provides a mock function for the type MockStore
func (_mock *MockStore) GetMarket(context1 context.Context, s string) (model.Market, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetMarket")
	}

	var r0 model.Market
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Market, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Market); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model.Market)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetMarket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMarket'
type MockStore_GetMarket_Call struct {
	*mock.Call
}

// GetMarket is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) GetMarket(context1 interface{}, s interface{}) *MockStore_GetMarket_Call {
	return &MockStore_GetMarket_Call{Call: _e.mock.On("GetMarket", context1, s)}
}

func (_c *MockStore_GetMarket_Call) Run(run func(context1 context.Context, s string)) *MockStore_GetMarket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetMarket_Call) Return(market model.Market, err error) *MockStore_GetMarket_Call {
	_c.Call.Return(market, err)
	return _c
}

func (_c *MockStore_GetMarket_Call) RunAndReturn(run func(context1 context.Context, s string) (model.Market, error)) *MockStore_GetMarket_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewsArticle provides a mock function for the type MockStore
func (_mock *MockStore) GetNewsArticle(context1 context.Context, s string) (model0.NewsArticle, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetNewsArticle")
	}

	var r0 model0.NewsArticle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model0.NewsArticle, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model0.NewsArticle); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model0.NewsArticle)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetNewsArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewsArticle'
type MockStore_GetNewsArticle_Call struct {
	*mock.Call
}

// GetNewsArticle is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) GetNewsArticle(context1 interface{}, s interface{}) *MockStore_GetNewsArticle_Call {
	return &MockStore_GetNewsArticle_Call{Call: _e.mock.On("GetNewsArticle", context1, s)}
}

func (_c *MockStore_GetNewsArticle_Call) Run(run func(context1 context.Context, s string)) *MockStore_GetNewsArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetNewsArticle_Call) Return(newsArticle model0.NewsArticle, err error) *MockStore_GetNewsArticle_Call {
	_c.Call.Return(newsArticle, err)
	return _c
}

func (_c *MockStore_GetNewsArticle_Call) RunAndReturn(run func(context1 context.Context, s string) (model0.NewsArticle, error)) *MockStore_GetNewsArticle_Call {
	_c.Call.Return(run)
	return _c
}

// GetPosition provides a mock function for the type MockStore
func (_mock *MockStore) GetPosition(context1 context.Context, s string) (model1.Position, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetPosition")
	}

	var r0 model1.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model1.Position, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model1.Position); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model1.Position)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPosition'
type MockStore_GetPosition_Call struct {
	*mock.Call
}

// GetPosition is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) GetPosition(context1 interface{}, s interface{}) *MockStore_GetPosition_Call {
	return &MockStore_GetPosition_Call{Call: _e.mock.On("GetPosition", context1, s)}
}

func (_c *MockStore_GetPosition_Call) Run(run func(context1 context.Context, s string)) *MockStore_GetPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetPosition_Call) Return(position model1.Position, err error) *MockStore_GetPosition_Call {
	_c.Call.Return(position, err)
	return _c
}

func (_c *MockStore_GetPosition_Call) RunAndReturn(run func(context1 context.Context, s string) (model1.Position, error)) *MockStore_GetPosition_Call {
	_c.Call.Return(run)
	return _c
}

// GetProbabilityDecision provides a mock function for the type MockStore
func (_mock *MockStore) GetProbabilityDecision(context1 context.Context, s string) (model2.ProbabilityDecision, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetProbabilityDecision")
	}

	var r0 model2.ProbabilityDecision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model2.ProbabilityDecision, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model2.ProbabilityDecision); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model2.ProbabilityDecision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetProbabilityDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProbabilityDecision'
type MockStore_GetProbabilityDecision_Call struct {
	*mock.Call
}

// GetProbabilityDecision is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) GetProbabilityDecision(context1 interface{}, s interface{}) *MockStore_GetProbabilityDecision_Call {
	return &MockStore_GetProbabilityDecision_Call{Call: _e.mock.On("GetProbabilityDecision", context1, s)}
}

func (_c *MockStore_GetProbabilityDecision_Call) Run(run func(context1 context.Context, s string)) *MockStore_GetProbabilityDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetProbabilityDecision_Call) Return(probabilityDecision model2.ProbabilityDecision, err error) *MockStore_GetProbabilityDecision_Call {
	_c.Call.Return(probabilityDecision, err)
	return _c
}

func (_c *MockStore_GetProbabilityDecision_Call) RunAndReturn(run func(context1 context.Context, s string) (model2.ProbabilityDecision, error)) *MockStore_GetProbabilityDecision_Call {
	_c.Call.Return(run)
	return _c
}

// GetRiskDecision provides a mock function for the type MockStore
func (_mock *MockStore) GetRiskDecision(context1 context.Context, s string) (model3.RiskDecision, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetRiskDecision")
	}

	var r0 model3.RiskDecision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model3.RiskDecision, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model3.RiskDecision); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model3.RiskDecision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRiskDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRiskDecision'
type MockStore_GetRiskDecision_Call struct {
	*mock.Call
}

// GetRiskDecision is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) GetRiskDecision(context1 interface{}, s interface{}) *MockStore_GetRiskDecision_Call {
	return &MockStore_GetRiskDecision_Call{Call: _e.mock.On("GetRiskDecision", context1, s)}
}

func (_c *MockStore_GetRiskDecision_Call) Run(run func(context1 context.Context, s string)) *MockStore_GetRiskDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetRiskDecision_Call) Return(riskDecision model3.RiskDecision, err error) *MockStore_GetRiskDecision_Call {
	_c.Call.Return(riskDecision, err)
	return _c
}

func (_c *MockStore_GetRiskDecision_Call) RunAndReturn(run func(context1 context.Context, s string) (model3.RiskDecision, error)) *MockStore_GetRiskDecision_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrade provides a mock function for the type MockStore
func (_mock *MockStore) GetTrade(context1 context.Context, s string) (model4.Trade, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetTrade")
	}

	var r0 model4.Trade
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model4.Trade, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model4.Trade); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(model4.Trade)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrade'
type MockStore_GetTrade_Call struct {
	*mock.Call
}

// GetTrade is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) GetTrade(context1 interface{}, s interface{}) *MockStore_GetTrade_Call {
	return &MockStore_GetTrade_Call{Call: _e.mock.On("GetTrade", context1, s)}
}

func (_c *MockStore_GetTrade_Call) Run(run func(context1 context.Context, s string)) *MockStore_GetTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetTrade_Call) Return(trade model4.Trade, err error) *MockStore_GetTrade_Call {
	_c.Call.Return(trade, err)
	return _c
}

func (_c *MockStore_GetTrade_Call) RunAndReturn(run func(context1 context.Context, s string) (model4.Trade, error)) *MockStore_GetTrade_Call {
	_c.Call.Return(run)
	return _c
}

// LatestAISignal provides a mock function for the type MockStore
func (_mock *MockStore) LatestAISignal(context1 context.Context, s string, s1 string) (model5.AISignal, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for LatestAISignal")
	}

	var r0 model5.AISignal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model5.AISignal, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model5.AISignal); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		r0 = ret.Get(0).(model5.AISignal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_LatestAISignal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestAISignal'
type MockStore_LatestAISignal_Call struct {
	*mock.Call
}

// LatestAISignal is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockStore_Expecter) LatestAISignal(context1 interface{}, s interface{}, s1 interface{}) *MockStore_LatestAISignal_Call {
	return &MockStore_LatestAISignal_Call{Call: _e.mock.On("LatestAISignal", context1, s, s1)}
}

func (_c *MockStore_LatestAISignal_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockStore_LatestAISignal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_LatestAISignal_Call) Return(aISignal model5.AISignal, err error) *MockStore_LatestAISignal_Call {
	_c.Call.Return(aISignal, err)
	return _c
}

func (_c *MockStore_LatestAISignal_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (model5.AISignal, error)) *MockStore_LatestAISignal_Call {
	_c.Call.Return(run)
	return _c
}

// ListAISignals provides a mock function for the type MockStore
func (_mock *MockStore) ListAISignals(context1 context.Context, s string, s1 string) ([]model5.AISignal, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for ListAISignals")
	}

	var r0 []model5.AISignal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]model5.AISignal, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []model5.AISignal); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model5.AISignal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListAISignals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAISignals'
type MockStore_ListAISignals_Call struct {
	*mock.Call
}

// ListAISignals is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockStore_Expecter) ListAISignals(context1 interface{}, s interface{}, s1 interface{}) *MockStore_ListAISignals_Call {
	return &MockStore_ListAISignals_Call{Call: _e.mock.On("ListAISignals", context1, s, s1)}
}

func (_c *MockStore_ListAISignals_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockStore_ListAISignals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_ListAISignals_Call) Return(aISignals []model5.AISignal, err error) *MockStore_ListAISignals_Call {
	_c.Call.Return(aISignals, err)
	return _c
}

func (_c *MockStore_ListAISignals_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) ([]model5.AISignal, error)) *MockStore_ListAISignals_Call {
	_c.Call.Return(run)
	return _c
}

// ListAudit provides a mock function for the type MockStore
func (_mock *MockStore) ListAudit(context1 context.Context, n int) ([]AuditLog, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for ListAudit")
	}

	var r0 []AuditLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]AuditLog, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []AuditLog); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAudit'
type MockStore_ListAudit_Call struct {
	*mock.Call
}

// ListAudit is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
func (_e *MockStore_Expecter) ListAudit(context1 interface{}, n interface{}) *MockStore_ListAudit_Call {
	return &MockStore_ListAudit_Call{Call: _e.mock.On("ListAudit", context1, n)}
}

func (_c *MockStore_ListAudit_Call) Run(run func(context1 context.Context, n int)) *MockStore_ListAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListAudit_Call) Return(auditLogs []AuditLog, err error) *MockStore_ListAudit_Call {
	_c.Call.Return(auditLogs, err)
	return _c
}

func (_c *MockStore_ListAudit_Call) RunAndReturn(run func(context1 context.Context, n int) ([]AuditLog, error)) *MockStore_ListAudit_Call {
	_c.Call.Return(run)
	return _c
}

// ListMarkets provides a mock function for the type MockStore
func (_mock *MockStore) ListMarkets(context1 context.Context) ([]model.Market, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListMarkets")
	}

	var r0 []model.Market
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Market, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Market); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Market)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListMarkets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMarkets'
type MockStore_ListMarkets_Call struct {
	*mock.Call
}

// ListMarkets is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockStore_Expecter) ListMarkets(context1 interface{}) *MockStore_ListMarkets_Call {
	return &MockStore_ListMarkets_Call{Call: _e.mock.On("ListMarkets", context1)}
}

func (_c *MockStore_ListMarkets_Call) Run(run func(context1 context.Context)) *MockStore_ListMarkets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_ListMarkets_Call) Return(markets []model.Market, err error) *MockStore_ListMarkets_Call {
	_c.Call.Return(markets, err)
	return _c
}

func (_c *MockStore_ListMarkets_Call) RunAndReturn(run func(context1 context.Context) ([]model.Market, error)) *MockStore_ListMarkets_Call {
	_c.Call.Return(run)
	return _c
}

// ListMatchesForNews provides a mock function for the type MockStore
func (_mock *MockStore) ListMatchesForNews(context1 context.Context, s string) ([]model6.NewsMarketMatch, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListMatchesForNews")
	}

	var r0 []model6.NewsMarketMatch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model6.NewsMarketMatch, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model6.NewsMarketMatch); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model6.NewsMarketMatch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListMatchesForNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMatchesForNews'
type MockStore_ListMatchesForNews_Call struct {
	*mock.Call
}

// ListMatchesForNews is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) ListMatchesForNews(context1 interface{}, s interface{}) *MockStore_ListMatchesForNews_Call {
	return &MockStore_ListMatchesForNews_Call{Call: _e.mock.On("ListMatchesForNews", context1, s)}
}

func (_c *MockStore_ListMatchesForNews_Call) Run(run func(context1 context.Context, s string)) *MockStore_ListMatchesForNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListMatchesForNews_Call) Return(newsMarketMatchs []model6.NewsMarketMatch, err error) *MockStore_ListMatchesForNews_Call {
	_c.Call.Return(newsMarketMatchs, err)
	return _c
}

func (_c *MockStore_ListMatchesForNews_Call) RunAndReturn(run func(context1 context.Context, s string) ([]model6.NewsMarketMatch, error)) *MockStore_ListMatchesForNews_Call {
	_c.Call.Return(run)
	return _c
}

// ListNewsArticles provides a mock function for the type MockStore
func (_mock *MockStore) ListNewsArticles(context1 context.Context, n int) ([]model0.NewsArticle, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for ListNewsArticles")
	}

	var r0 []model0.NewsArticle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model0.NewsArticle, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model0.NewsArticle); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model0.NewsArticle)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListNewsArticles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNewsArticles'
type MockStore_ListNewsArticles_Call struct {
	*mock.Call
}

// ListNewsArticles is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
func (_e *MockStore_Expecter) ListNewsArticles(context1 interface{}, n interface{}) *MockStore_ListNewsArticles_Call {
	return &MockStore_ListNewsArticles_Call{Call: _e.mock.On("ListNewsArticles", context1, n)}
}

func (_c *MockStore_ListNewsArticles_Call) Run(run func(context1 context.Context, n int)) *MockStore_ListNewsArticles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListNewsArticles_Call) Return(newsArticles []model0.NewsArticle, err error) *MockStore_ListNewsArticles_Call {
	_c.Call.Return(newsArticles, err)
	return _c
}

func (_c *MockStore_ListNewsArticles_Call) RunAndReturn(run func(context1 context.Context, n int) ([]model0.NewsArticle, error)) *MockStore_ListNewsArticles_Call {
	_c.Call.Return(run)
	return _c
}

// ListPositions provides a mock function for the type MockStore
func (_mock *MockStore) ListPositions(context1 context.Context, s string) ([]model1.Position, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListPositions")
	}

	var r0 []model1.Position
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model1.Position, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model1.Position); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model1.Position)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPositions'
type MockStore_ListPositions_Call struct {
	*mock.Call
}

// ListPositions is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockStore_Expecter) ListPositions(context1 interface{}, s interface{}) *MockStore_ListPositions_Call {
	return &MockStore_ListPositions_Call{Call: _e.mock.On("ListPositions", context1, s)}
}

func (_c *MockStore_ListPositions_Call) Run(run func(context1 context.Context, s string)) *MockStore_ListPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListPositions_Call) Return(positions []model1.Position, err error) *MockStore_ListPositions_Call {
	_c.Call.Return(positions, err)
	return _c
}

func (_c *MockStore_ListPositions_Call) RunAndReturn(run func(context1 context.Context, s string) ([]model1.Position, error)) *MockStore_ListPositions_Call {
	_c.Call.Return(run)
	return _c
}

// ListProbabilityDecisions provides a mock function for the type MockStore
func (_mock *MockStore) ListProbabilityDecisions(context1 context.Context, n int) ([]model2.ProbabilityDecision, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for ListProbabilityDecisions")
	}

	var r0 []model2.ProbabilityDecision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model2.ProbabilityDecision, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model2.ProbabilityDecision); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model2.ProbabilityDecision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListProbabilityDecisions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProbabilityDecisions'
type MockStore_ListProbabilityDecisions_Call struct {
	*mock.Call
}

// ListProbabilityDecisions is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
func (_e *MockStore_Expecter) ListProbabilityDecisions(context1 interface{}, n interface{}) *MockStore_ListProbabilityDecisions_Call {
	return &MockStore_ListProbabilityDecisions_Call{Call: _e.mock.On("ListProbabilityDecisions", context1, n)}
}

func (_c *MockStore_ListProbabilityDecisions_Call) Run(run func(context1 context.Context, n int)) *MockStore_ListProbabilityDecisions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListProbabilityDecisions_Call) Return(probabilityDecisions []model2.ProbabilityDecision, err error) *MockStore_ListProbabilityDecisions_Call {
	_c.Call.Return(probabilityDecisions, err)
	return _c
}

func (_c *MockStore_ListProbabilityDecisions_Call) RunAndReturn(run func(context1 context.Context, n int) ([]model2.ProbabilityDecision, error)) *MockStore_ListProbabilityDecisions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRiskDecisions provides a mock function for the type MockStore
func (_mock *MockStore) ListRiskDecisions(context1 context.Context, n int) ([]model3.RiskDecision, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for ListRiskDecisions")
	}

	var r0 []model3.RiskDecision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model3.RiskDecision, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model3.RiskDecision); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model3.RiskDecision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListRiskDecisions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRiskDecisions'
type MockStore_ListRiskDecisions_Call struct {
	*mock.Call
}

// ListRiskDecisions is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
func (_e *MockStore_Expecter) ListRiskDecisions(context1 interface{}, n interface{}) *MockStore_ListRiskDecisions_Call {
	return &MockStore_ListRiskDecisions_Call{Call: _e.mock.On("ListRiskDecisions", context1, n)}
}

func (_c *MockStore_ListRiskDecisions_Call) Run(run func(context1 context.Context, n int)) *MockStore_ListRiskDecisions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListRiskDecisions_Call) Return(riskDecisions []model3.RiskDecision, err error) *MockStore_ListRiskDecisions_Call {
	_c.Call.Return(riskDecisions, err)
	return _c
}

func (_c *MockStore_ListRiskDecisions_Call) RunAndReturn(run func(context1 context.Context, n int) ([]model3.RiskDecision, error)) *MockStore_ListRiskDecisions_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrades provides a mock function for the type MockStore
func (_mock *MockStore) ListTrades(context1 context.Context, n int) ([]model4.Trade, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for ListTrades")
	}

	var r0 []model4.Trade
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model4.Trade, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model4.Trade); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model4.Trade)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrades'
type MockStore_ListTrades_Call struct {
	*mock.Call
}

// ListTrades is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
func (_e *MockStore_Expecter) ListTrades(context1 interface{}, n interface{}) *MockStore_ListTrades_Call {
	return &MockStore_ListTrades_Call{Call: _e.mock.On("ListTrades", context1, n)}
}

func (_c *MockStore_ListTrades_Call) Run(run func(context1 context.Context, n int)) *MockStore_ListTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListTrades_Call) Return(trades []model4.Trade, err error) *MockStore_ListTrades_Call {
	_c.Call.Return(trades, err)
	return _c
}

func (_c *MockStore_ListTrades_Call) RunAndReturn(run func(context1 context.Context, n int) ([]model4.Trade, error)) *MockStore_ListTrades_Call {
	_c.Call.Return(run)
	return _c
}

// Portfolio provides a mock function for the type MockStore
func (_mock *MockStore) Portfolio(context1 context.Context, f float64) (model3.PortfolioState, error) {
	ret := _mock.Called(context1, f)

	if len(ret) == 0 {
		panic("no return value specified for Portfolio")
	}

	var r0 model3.PortfolioState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, float64) (model3.PortfolioState, error)); ok {
		return returnFunc(context1, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, float64) model3.PortfolioState); ok {
		r0 = returnFunc(context1, f)
	} else {
		r0 = ret.Get(0).(model3.PortfolioState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, float64) error); ok {
		r1 = returnFunc(context1, f)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Portfolio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Portfolio'
type MockStore_Portfolio_Call struct {
	*mock.Call
}

// Portfolio is a helper method to define mock.On call
//   - context1 context.Context
//   - f float64
func (_e *MockStore_Expecter) Portfolio(context1 interface{}, f interface{}) *MockStore_Portfolio_Call {
	return &MockStore_Portfolio_Call{Call: _e.mock.On("Portfolio", context1, f)}
}

func (_c *MockStore_Portfolio_Call) Run(run func(context1 context.Context, f float64)) *MockStore_Portfolio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_Portfolio_Call) Return(portfolioState model3.PortfolioState, err error) *MockStore_Portfolio_Call {
	_c.Call.Return(portfolioState, err)
	return _c
}

func (_c *MockStore_Portfolio_Call) RunAndReturn(run func(context1 context.Context, f float64) (model3.PortfolioState, error)) *MockStore_Portfolio_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAISignal provides a mock function for the type MockStore
func (_mock *MockStore) SaveAISignal(context1 context.Context, aISignal model5.AISignal) error {
	ret := _mock.Called(context1, aISignal)

	if len(ret) == 0 {
		panic("no return value specified for SaveAISignal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model5.AISignal) error); ok {
		r0 = returnFunc(context1, aISignal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveAISignal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAISignal'
type MockStore_SaveAISignal_Call struct {
	*mock.Call
}

// SaveAISignal is a helper method to define mock.On call
//   - context1 context.Context
//   - aISignal model5.AISignal
func (_e *MockStore_Expecter) SaveAISignal(context1 interface{}, aISignal interface{}) *MockStore_SaveAISignal_Call {
	return &MockStore_SaveAISignal_Call{Call: _e.mock.On("SaveAISignal", context1, aISignal)}
}

func (_c *MockStore_SaveAISignal_Call) Run(run func(context1 context.Context, aISignal model5.AISignal)) *MockStore_SaveAISignal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model5.AISignal
		if args[1] != nil {
			arg1 = args[1].(model5.AISignal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveAISignal_Call) Return(err error) *MockStore_SaveAISignal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveAISignal_Call) RunAndReturn(run func(context1 context.Context, aISignal model5.AISignal) error) *MockStore_SaveAISignal_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAudit provides a mock function for the type MockStore
func (_mock *MockStore) SaveAudit(context1 context.Context, auditLog AuditLog) error {
	ret := _mock.Called(context1, auditLog)

	if len(ret) == 0 {
		panic("no return value specified for SaveAudit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AuditLog) error); ok {
		r0 = returnFunc(context1, auditLog)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAudit'
type MockStore_SaveAudit_Call struct {
	*mock.Call
}

// SaveAudit is a helper method to define mock.On call
//   - context1 context.Context
//   - auditLog AuditLog
func (_e *MockStore_Expecter) SaveAudit(context1 interface{}, auditLog interface{}) *MockStore_SaveAudit_Call {
	return &MockStore_SaveAudit_Call{Call: _e.mock.On("SaveAudit", context1, auditLog)}
}

func (_c *MockStore_SaveAudit_Call) Run(run func(context1 context.Context, auditLog AuditLog)) *MockStore_SaveAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AuditLog
		if args[1] != nil {
			arg1 = args[1].(AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveAudit_Call) Return(err error) *MockStore_SaveAudit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveAudit_Call) RunAndReturn(run func(context1 context.Context, auditLog AuditLog) error) *MockStore_SaveAudit_Call {
	_c.Call.Return(run)
	return _c
}

// SaveLiveMarketState provides a mock function for the type MockStore
func (_mock *MockStore) SaveLiveMarketState(context1 context.Context, liveMarketState model.LiveMarketState) error {
	ret := _mock.Called(context1, liveMarketState)

	if len(ret) == 0 {
		panic("no return value specified for SaveLiveMarketState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.LiveMarketState) error); ok {
		r0 = returnFunc(context1, liveMarketState)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveLiveMarketState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLiveMarketState'
type MockStore_SaveLiveMarketState_Call struct {
	*mock.Call
}

// SaveLiveMarketState is a helper method to define mock.On call
//   - context1 context.Context
//   - liveMarketState model.LiveMarketState
func (_e *MockStore_Expecter) SaveLiveMarketState(context1 interface{}, liveMarketState interface{}) *MockStore_SaveLiveMarketState_Call {
	return &MockStore_SaveLiveMarketState_Call{Call: _e.mock.On("SaveLiveMarketState", context1, liveMarketState)}
}

func (_c *MockStore_SaveLiveMarketState_Call) Run(run func(context1 context.Context, liveMarketState model.LiveMarketState)) *MockStore_SaveLiveMarketState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.LiveMarketState
		if args[1] != nil {
			arg1 = args[1].(model.LiveMarketState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveLiveMarketState_Call) Return(err error) *MockStore_SaveLiveMarketState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveLiveMarketState_Call) RunAndReturn(run func(context1 context.Context, liveMarketState model.LiveMarketState) error) *MockStore_SaveLiveMarketState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMarkets provides a mock function for the type MockStore
func (_mock *MockStore) SaveMarkets(context1 context.Context, markets []model.Market) error {
	ret := _mock.Called(context1, markets)

	if len(ret) == 0 {
		panic("no return value specified for SaveMarkets")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.Market) error); ok {
		r0 = returnFunc(context1, markets)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveMarkets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMarkets'
type MockStore_SaveMarkets_Call struct {
	*mock.Call
}

// SaveMarkets is a helper method to define mock.On call
//   - context1 context.Context
//   - markets []model.Market
func (_e *MockStore_Expecter) SaveMarkets(context1 interface{}, markets interface{}) *MockStore_SaveMarkets_Call {
	return &MockStore_SaveMarkets_Call{Call: _e.mock.On("SaveMarkets", context1, markets)}
}

func (_c *MockStore_SaveMarkets_Call) Run(run func(context1 context.Context, markets []model.Market)) *MockStore_SaveMarkets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.Market
		if args[1] != nil {
			arg1 = args[1].([]model.Market)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveMarkets_Call) Return(err error) *MockStore_SaveMarkets_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveMarkets_Call) RunAndReturn(run func(context1 context.Context, markets []model.Market) error) *MockStore_SaveMarkets_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMatch provides a mock function for the type MockStore
func (_mock *MockStore) SaveMatch(context1 context.Context, newsMarketMatch model6.NewsMarketMatch) error {
	ret := _mock.Called(context1, newsMarketMatch)

	if len(ret) == 0 {
		panic("no return value specified for SaveMatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model6.NewsMarketMatch) error); ok {
		r0 = returnFunc(context1, newsMarketMatch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMatch'
type MockStore_SaveMatch_Call struct {
	*mock.Call
}

// SaveMatch is a helper method to define mock.On call
//   - context1 context.Context
//   - newsMarketMatch model6.NewsMarketMatch
func (_e *MockStore_Expecter) SaveMatch(context1 interface{}, newsMarketMatch interface{}) *MockStore_SaveMatch_Call {
	return &MockStore_SaveMatch_Call{Call: _e.mock.On("SaveMatch", context1, newsMarketMatch)}
}

func (_c *MockStore_SaveMatch_Call) Run(run func(context1 context.Context, newsMarketMatch model6.NewsMarketMatch)) *MockStore_SaveMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model6.NewsMarketMatch
		if args[1] != nil {
			arg1 = args[1].(model6.NewsMarketMatch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveMatch_Call) Return(err error) *MockStore_SaveMatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveMatch_Call) RunAndReturn(run func(context1 context.Context, newsMarketMatch model6.NewsMarketMatch) error) *MockStore_SaveMatch_Call {
	_c.Call.Return(run)
	return _c
}

// SaveNewsArticles provides a mock function for the type MockStore
func (_mock *MockStore) SaveNewsArticles(context1 context.Context, newsArticles []model0.NewsArticle) error {
	ret := _mock.Called(context1, newsArticles)

	if len(ret) == 0 {
		panic("no return value specified for SaveNewsArticles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model0.NewsArticle) error); ok {
		r0 = returnFunc(context1, newsArticles)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveNewsArticles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveNewsArticles'
type MockStore_SaveNewsArticles_Call struct {
	*mock.Call
}

// SaveNewsArticles is a helper method to define mock.On call
//   - context1 context.Context
//   - newsArticles []model0.NewsArticle
func (_e *MockStore_Expecter) SaveNewsArticles(context1 interface{}, newsArticles interface{}) *MockStore_SaveNewsArticles_Call {
	return &MockStore_SaveNewsArticles_Call{Call: _e.mock.On("SaveNewsArticles", context1, newsArticles)}
}

func (_c *MockStore_SaveNewsArticles_Call) Run(run func(context1 context.Context, newsArticles []model0.NewsArticle)) *MockStore_SaveNewsArticles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model0.NewsArticle
		if args[1] != nil {
			arg1 = args[1].([]model0.NewsArticle)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveNewsArticles_Call) Return(err error) *MockStore_SaveNewsArticles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveNewsArticles_Call) RunAndReturn(run func(context1 context.Context, newsArticles []model0.NewsArticle) error) *MockStore_SaveNewsArticles_Call {
	_c.Call.Return(run)
	return _c
}

// SavePosition provides a mock function for the type MockStore
func (_mock *MockStore) SavePosition(context1 context.Context, position model1.Position) error {
	ret := _mock.Called(context1, position)

	if len(ret) == 0 {
		panic("no return value specified for SavePosition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model1.Position) error); ok {
		r0 = returnFunc(context1, position)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SavePosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePosition'
type MockStore_SavePosition_Call struct {
	*mock.Call
}

// SavePosition is a helper method to define mock.On call
//   - context1 context.Context
//   - position model1.Position
func (_e *MockStore_Expecter) SavePosition(context1 interface{}, position interface{}) *MockStore_SavePosition_Call {
	return &MockStore_SavePosition_Call{Call: _e.mock.On("SavePosition", context1, position)}
}

func (_c *MockStore_SavePosition_Call) Run(run func(context1 context.Context, position model1.Position)) *MockStore_SavePosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model1.Position
		if args[1] != nil {
			arg1 = args[1].(model1.Position)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SavePosition_Call) Return(err error) *MockStore_SavePosition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SavePosition_Call) RunAndReturn(run func(context1 context.Context, position model1.Position) error) *MockStore_SavePosition_Call {
	_c.Call.Return(run)
	return _c
}

// SaveProbabilityDecision provides a mock function for the type MockStore
func (_mock *MockStore) SaveProbabilityDecision(context1 context.Context, probabilityDecision model2.ProbabilityDecision) error {
	ret := _mock.Called(context1, probabilityDecision)

	if len(ret) == 0 {
		panic("no return value specified for SaveProbabilityDecision")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model2.ProbabilityDecision) error); ok {
		r0 = returnFunc(context1, probabilityDecision)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveProbabilityDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProbabilityDecision'
type MockStore_SaveProbabilityDecision_Call struct {
	*mock.Call
}

// SaveProbabilityDecision is a helper method to define mock.On call
//   - context1 context.Context
//   - probabilityDecision model2.ProbabilityDecision
func (_e *MockStore_Expecter) SaveProbabilityDecision(context1 interface{}, probabilityDecision interface{}) *MockStore_SaveProbabilityDecision_Call {
	return &MockStore_SaveProbabilityDecision_Call{Call: _e.mock.On("SaveProbabilityDecision", context1, probabilityDecision)}
}

func (_c *MockStore_SaveProbabilityDecision_Call) Run(run func(context1 context.Context, probabilityDecision model2.ProbabilityDecision)) *MockStore_SaveProbabilityDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model2.ProbabilityDecision
		if args[1] != nil {
			arg1 = args[1].(model2.ProbabilityDecision)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveProbabilityDecision_Call) Return(err error) *MockStore_SaveProbabilityDecision_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveProbabilityDecision_Call) RunAndReturn(run func(context1 context.Context, probabilityDecision model2.ProbabilityDecision) error) *MockStore_SaveProbabilityDecision_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRiskDecision provides a mock function for the type MockStore
func (_mock *MockStore) SaveRiskDecision(context1 context.Context, riskDecision model3.RiskDecision) error {
	ret := _mock.Called(context1, riskDecision)

	if len(ret) == 0 {
		panic("no return value specified for SaveRiskDecision")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model3.RiskDecision) error); ok {
		r0 = returnFunc(context1, riskDecision)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveRiskDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRiskDecision'
type MockStore_SaveRiskDecision_Call struct {
	*mock.Call
}

// SaveRiskDecision is a helper method to define mock.On call
//   - context1 context.Context
//   - riskDecision model3.RiskDecision
func (_e *MockStore_Expecter) SaveRiskDecision(context1 interface{}, riskDecision interface{}) *MockStore_SaveRiskDecision_Call {
	return &MockStore_SaveRiskDecision_Call{Call: _e.mock.On("SaveRiskDecision", context1, riskDecision)}
}

func (_c *MockStore_SaveRiskDecision_Call) Run(run func(context1 context.Context, riskDecision model3.RiskDecision)) *MockStore_SaveRiskDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model3.RiskDecision
		if args[1] != nil {
			arg1 = args[1].(model3.RiskDecision)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveRiskDecision_Call) Return(err error) *MockStore_SaveRiskDecision_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveRiskDecision_Call) RunAndReturn(run func(context1 context.Context, riskDecision model3.RiskDecision) error) *MockStore_SaveRiskDecision_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTrade provides a mock function for the type MockStore
func (_mock *MockStore) SaveTrade(context1 context.Context, trade model4.Trade) error {
	ret := _mock.Called(context1, trade)

	if len(ret) == 0 {
		panic("no return value specified for SaveTrade")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model4.Trade) error); ok {
		r0 = returnFunc(context1, trade)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SaveTrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTrade'
type MockStore_SaveTrade_Call struct {
	*mock.Call
}

// SaveTrade is a helper method to define mock.On call
//   - context1 context.Context
//   - trade model4.Trade
func (_e *MockStore_Expecter) SaveTrade(context1 interface{}, trade interface{}) *MockStore_SaveTrade_Call {
	return &MockStore_SaveTrade_Call{Call: _e.mock.On("SaveTrade", context1, trade)}
}

func (_c *MockStore_SaveTrade_Call) Run(run func(context1 context.Context, trade model4.Trade)) *MockStore_SaveTrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model4.Trade
		if args[1] != nil {
			arg1 = args[1].(model4.Trade)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_SaveTrade_Call) Return(err error) *MockStore_SaveTrade_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SaveTrade_Call) RunAndReturn(run func(context1 context.Context, trade model4.Trade) error) *MockStore_SaveTrade_Call {
	_c.Call.Return(run)
	return _c
}
